[package]
name = "longest-common-prefix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
common = { path = "../../common" }
rstest = "0.16.0"
