[package]
name = "k-closest-points-to-origin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rstest = "0.15.0"
spectral = "0.6.0"
