[package]
name = "common"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.15.0"
proptest = "1.0.0"
lazy_static = "1.4.0"
rand = "0.8.5"
spectral = "0.6.0"
