[package]
name = "common"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
proptest = "1.0.0"
rand = "0.8.5"
rstest = "0.15.0"
