[package]
name = "delete_the_middle_node_of_a_linked_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asserter = "0.1.0"
common = { path = "../../common" }
proptest = "1.0.0"
